# Generated by Django 4.0.2 on 2022-04-14 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0003_alter_reservation_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='is_reserved',
            field=models.BooleanField(default=False),
        ),
    ]
