# Generated by Django 4.0.2 on 2022-04-14 20:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0002_food_img'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Категория', 'verbose_name_plural': 'Категории'},
        ),
        migrations.AlterModelOptions(
            name='food',
            options={'verbose_name': 'Блюдо', 'verbose_name_plural': 'Блюда'},
        ),
    ]
