# Generated by Django 4.0.2 on 2022-05-07 20:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order_list', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name': 'Заказ'},
        ),
        migrations.AlterModelOptions(
            name='orderitem',
            options={'verbose_name': 'Элемент заказа'},
        ),
    ]
