# Generated by Django 4.0.2 on 2022-05-08 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_list', '0003_alter_order_options_alter_orderitem_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='date_order',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата заказа'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='date_add',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
