# Generated by Django 4.0.2 on 2022-05-12 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_list', '0005_alter_order_options_alter_order_customer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='time_order',
            field=models.TimeField(auto_now=True, verbose_name='Время заказа'),
        ),
        migrations.AlterField(
            model_name='order',
            name='date_order',
            field=models.DateField(auto_now=True, verbose_name='Дата заказа'),
        ),
    ]
