# Generated by Django 4.0.2 on 2022-05-12 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_list', '0006_order_time_order_alter_order_date_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(default='готовится', max_length=30),
        ),
    ]
