# Generated by Django 4.0.2 on 2022-05-13 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_list', '0007_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='date_order',
            field=models.DateField(auto_now_add=True, verbose_name='Дата заказа'),
        ),
        migrations.AlterField(
            model_name='order',
            name='time_order',
            field=models.TimeField(auto_now_add=True, verbose_name='Время заказа'),
        ),
    ]
